// <auto-generated />
namespace APITecsup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gaseosas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gaseosas));
        
        string IMigrationMetadata.Id
        {
            get { return "202112090340493_Gaseosas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
